name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run linter
        run: >
          ./gradlew 
          ktlintCheck

      - name: Run tests
        run: >
          ./gradlew 
          test
          koverXmlReport

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit Test Report
          report_paths: '**/build/test-results/**/TEST-*.xml'
          annotate_notice: false

      - name: Publish Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@db72e7e7c96f98d239967958b0a0a6ca7d3bb45f
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/kover/report.xml
          token: ${{ github.token }}
